name: Build DIE-sort

on:
  workflow_dispatch:
  release:
    types: [created]
  schedule:
    - cron: '0 0 * * MON'

env:
  SRC_PATH: ${{ github.workspace }}/src
  SRC_PATH_WIN: ${{ github.workspace }}\src
  RELEASE_PATH: ${{ github.workspace }}/src/release

jobs:       
  build-windows-32:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
         submodules: 'recursive'
         path: ${{ env.SRC_PATH }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86
          vs-version: '[16.0,17.0)'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_msvc2019'
          dir: ${{ github.workspace }}
          modules: qtscript

      - name: Build
        shell: cmd
        working-directory: ${{ env.SRC_PATH }}
        run: |
          echo on
          call ${{ env.SRC_PATH_WIN }}\build_win32.bat"
          
      - name: Upload Release as Download
        uses: softprops/action-gh-release@v2
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: Beta
          release_name: Beta
          draft: false
          prerelease: true
          files: |
            ${{ env.RELEASE_PATH }}/*.zip

#       working-directory: ${{ env.SRC_PATH }}
#       run: |
#         bash -x build_mac.sh
